// <auto-generated />
namespace LocationVoiture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FkAdded1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FkAdded1));
        
        string IMigrationMetadata.Id
        {
            get { return "202102031531475_FkAdded1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
