// <auto-generated />
namespace LocationVoiture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_column_special_voiture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_column_special_voiture));
        
        string IMigrationMetadata.Id
        {
            get { return "202212291735517_add_column_special_voiture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
